// Syllabus completo — 10 disciplinas técnicas + 6 níveis CEFR de Inglês Técnico.
// Cada lição aqui vira uma chamada real ao motor de geração (scripts/generate-content.mjs).

export const TECH_DISCIPLINES = [
  {
    id: 'logic-algorithms', name: 'Lógica e Algoritmos', icon: 'terminal', color: '#22c55e',
    description: 'Pensamento computacional, complexidade e estratégias de resolução de problemas.',
    lessons: [
      'Pensamento computacional: decompor problemas como um dev',
      'Condicionais na prática: fluxos de decisão reais',
      'Laços de repetição: for, while e quando usar cada um',
      'Recursão sem medo: casos base e chamadas empilhadas',
      'Notação Big-O aplicada: medindo custo de tempo',
      'Complexidade de espaço: memória também tem preço',
      'Força bruta e dividir para conquistar',
      'Algoritmos gulosos: decisões locais, resultado global',
      'Programação dinâmica introdutória: memoização',
      'Pseudocódigo profissional: comunicar antes de codar',
    ],
  },
  {
    id: 'programming-languages', name: 'Lógica de Programação Multi-linguagem', icon: 'code', color: '#3b82f6',
    description: 'Python, JavaScript, Java e C++ lado a lado: sintaxe, POO e paradigmas.',
    lessons: [
      'Sintaxe básica comparada: Python vs JavaScript',
      'Tipos e variáveis: tipagem estática vs dinâmica',
      'Estruturas de controle nas 4 linguagens',
      'Funções, parâmetros e escopo',
      'Tratamento de erros e exceções',
      'POO parte 1: classes e objetos',
      'POO parte 2: herança e polimorfismo',
      'POO parte 3: encapsulamento e interfaces',
      'Gerenciamento de memória: GC vs manual',
      'Traduzindo código entre linguagens (exercício avançado)',
    ],
  },
  {
    id: 'data-structures', name: 'Estruturas de Dados', icon: 'layers', color: '#8b5cf6',
    description: 'Da lista ligada ao grafo: escolher a estrutura certa para cada problema.',
    lessons: [
      'Arrays e listas: acesso, inserção e custo',
      'Pilhas: LIFO no mundo real (undo, call stack)',
      'Filas: FIFO, deques e filas de prioridade',
      'Listas ligadas: ponteiros e trade-offs',
      'Árvores binárias e árvores de busca',
      'Balanceamento introdutório: por que AVL existe',
      'Tabelas hash: colisões e fatores de carga',
      'Grafos: representação com matriz e lista',
      'BFS e DFS: percorrendo grafos',
      'Escolhendo a estrutura certa: estudo de casos',
    ],
  },
  {
    id: 'databases', name: 'Sistemas e Bancos de Dados', icon: 'database', color: '#f59e0b',
    description: 'Modelo relacional, SQL de verdade e quando escolher NoSQL.',
    lessons: [
      'Modelo relacional: tabelas, chaves e integridade',
      'SELECT e WHERE: consultando dados de verdade',
      'JOINs: combinando tabelas sem medo',
      'GROUP BY e agregações',
      'Subqueries e CTEs',
      'Índices: por que sua query está lenta',
      'Transações e ACID',
      'Normalização: 1FN, 2FN e 3FN na prática',
      'NoSQL: documentos, chave-valor e grafos',
      'Modelando o banco de um e-commerce (guiado)',
    ],
  },
  {
    id: 'software-design', name: 'Design de Software e APIs', icon: 'blocks', color: '#ec4899',
    description: 'SOLID, padrões GoF e design de APIs REST/GraphQL.',
    lessons: [
      'Princípios SOLID parte 1: SRP e OCP',
      'Princípios SOLID parte 2: LSP, ISP e DIP',
      'Padrões criacionais: Singleton, Factory e Builder',
      'Padrões criacionais: Abstract Factory e Prototype',
      'Padrões estruturais: Adapter, Facade e Decorator',
      'Padrões estruturais: Composite, Proxy, Bridge e Flyweight',
      'Padrões comportamentais: Strategy, Observer e Command',
      'Padrões comportamentais: State, Template Method e Iterator',
      'REST na prática: verbos, status codes e versionamento',
      'Paginação, autenticação com tokens e GraphQL',
      'Contratos de API: OpenAPI/Swagger como conceito',
    ],
  },
  {
    id: 'cloud-devops', name: 'Cloud e DevOps', icon: 'cloud', color: '#06b6d4',
    description: 'Nuvem, containers, CI/CD e observabilidade sem pagar nada.',
    lessons: [
      'IaaS, PaaS e SaaS: quem gerencia o quê',
      'AWS, GCP e Azure: mapa comparativo dos serviços',
      'Computação na nuvem: VMs e serverless',
      'Armazenamento e bancos gerenciados',
      'Docker parte 1: o que é um container',
      'Docker parte 2: escrevendo um Dockerfile',
      'CI/CD: o que é e por que muda tudo',
      'GitHub Actions na prática',
      'Observabilidade: logs, métricas e alertas',
      'Free tiers: montando infra de estudo sem custo',
    ],
  },
  {
    id: 'testing', name: 'Testes', icon: 'flask', color: '#84cc16',
    description: 'Pirâmide de testes, TDD e frameworks por linguagem.',
    lessons: [
      'Pirâmide de testes: unidade, integração e E2E',
      'Testes unitários: o que testar (e o que não)',
      'Isolando dependências: mocks e stubs',
      'Testes de integração: onde os bugs se escondem',
      'TDD parte 1: red, green, refactor',
      'TDD parte 2: praticando o ciclo em um kata',
      'pytest: testando Python de verdade',
      'Jest: testando JavaScript de verdade',
      'JUnit: testando Java de verdade',
      'Cobertura de testes: métrica útil ou vaidade?',
    ],
  },
  {
    id: 'git-versioning', name: 'Versionamento de Código', icon: 'git-branch', color: '#f97316',
    description: 'Git na prática, fluxo colaborativo e GitHub.',
    lessons: [
      'Git essencial: init, add, commit',
      'Branches: trabalhando em paralelo',
      'Merge vs rebase: quando usar cada um',
      'Resolvendo conflitos sem pânico',
      'Boas mensagens de commit (em inglês!)',
      'Pull requests e code review',
      'GitHub: issues, projects e colaboração',
      'GitHub Actions básicas no seu repositório',
      'Desfazendo coisas: reset, revert e reflog',
      'Fluxos de trabalho: GitHub Flow vs Git Flow',
    ],
  },
  {
    id: 'agile', name: 'Metodologias Ágeis', icon: 'kanban', color: '#a855f7',
    description: 'Scrum, Kanban e o vocabulário real de um squad.',
    lessons: [
      'Manifesto Ágil: o que realmente diz',
      'Scrum: papéis do time',
      'Cerimônias: daily, planning, review e retro',
      'Sprint e backlog: organizando o trabalho',
      'Story points e estimativas',
      'Kanban: fluxo contínuo e WIP limits',
      'Scrum vs Kanban: quando cada um encaixa',
      'Vocabulário de squad em inglês: grooming, refinement',
      'Métricas ágeis: velocity, lead time, cycle time',
      'Anti-padrões ágeis: o que evitar no dia a dia',
    ],
  },
  {
    id: 'soft-skills', name: 'Habilidades Comportamentais', icon: 'users', color: '#14b8a6',
    description: 'Resolução de problemas, comunicação técnica e feedback.',
    lessons: [
      'Causa raiz: os 5 porquês aplicados a bugs',
      'Pensamento estruturado para investigar falhas',
      'Traduzindo pedido de negócio em requisito técnico',
      'Escrevendo um relato de bug claro',
      'Comunicação assíncrona: escrever bem economiza reunião',
      'Dando feedback em code review',
      'Recebendo feedback sem levar para o pessoal',
      'Priorizando quando tudo é urgente',
      'Explicando decisões técnicas para não-técnicos',
      'Simulação: cliente vago, requisitos claros (avaliado por IA)',
    ],
  },
];

export const ENGLISH_LEVELS = [
  {
    id: 'english-a1', cefr: 'A1', name: 'Inglês Técnico A1', icon: 'flag', color: '#4ade80',
    description: 'Vocabulário essencial de TI e primeiras frases profissionais.',
    lessons: [
      'Hardware words: parts of a computer',
      'Software words: apps, files and programs',
      'The internet: browser, website, download',
      'Basic code words: variable, function, error',
      'Introducing yourself at work',
      'Numbers, versions and dates in English',
      'Simple error messages: reading your first errors',
      'UI words: button, menu, screen, click',
      'Saying tech acronyms out loud: API, URL, HTML',
      'Asking for help: simple questions at work',
    ],
  },
  {
    id: 'english-a2', cefr: 'A2', name: 'Inglês Técnico A2', icon: 'flag', color: '#34d399',
    description: 'Frases completas sobre trabalho, código e problemas simples.',
    lessons: [
      'Talking about your daily tasks',
      'Describing a simple bug',
      'Reading short README files',
      'Writing your first commit message',
      'Present continuous: what are you working on?',
      'Folder, path and file operations in English',
      'Simple past: what did you do yesterday? (standup basics)',
      'Comparing tools: faster, easier, better',
      'Short emails: asking and answering',
      'Listening: slow tech dialogues',
    ],
  },
  {
    id: 'english-b1', cefr: 'B1', name: 'Inglês Técnico B1', icon: 'globe', color: '#2dd4bf',
    description: 'Documentação real, standups e conversas de trabalho.',
    lessons: [
      'Reading real documentation: READMEs and changelogs',
      'Stack Overflow: reading questions and answers',
      'Writing good commit messages and PR descriptions',
      'The daily standup: yesterday, today, blockers',
      'Explaining a bug to a teammate',
      'Conditionals for developers: if it fails, we roll back',
      'Reading full error messages and stack traces',
      'Writing short professional emails',
      'Listening: tutorial excerpts at natural speed',
      'Meetings vocabulary: agenda, follow-up, action items',
    ],
  },
  {
    id: 'english-b2', cefr: 'B2', name: 'Inglês Técnico B2', icon: 'globe', color: '#22d3ee',
    description: 'Discussões técnicas, code review e escrita estruturada.',
    lessons: [
      'Code review language: suggesting without offending',
      'Writing a clear bug report in English',
      'Discussing trade-offs: pros, cons and alternatives',
      'Passive voice in technical writing',
      'Reading API documentation in depth',
      'Explaining architecture decisions',
      'Listening: conference talk excerpts',
      'Writing a project README from scratch',
      'Disagreeing politely in technical discussions',
      'Phrasal verbs developers actually use',
    ],
  },
  {
    id: 'english-c1', cefr: 'C1', name: 'Inglês Técnico C1', icon: 'award', color: '#38bdf8',
    description: 'Design docs, RFCs e entrevistas técnicas.',
    lessons: [
      'Reading RFCs and technical specifications',
      'Writing a simple design document',
      'Technical interview: talking about your experience',
      'Technical interview: explaining your solution',
      'Nuance and hedging: it depends, arguably, roughly',
      'Listening: fast-paced podcast discussions',
      'Writing detailed post-mortems',
      'Idioms and expressions in tech workplaces',
      'Persuasive writing: proposing a migration',
      'Negotiating scope and deadlines',
    ],
  },
  {
    id: 'english-c2', cefr: 'C2', name: 'Inglês Técnico C2', icon: 'award', color: '#60a5fa',
    description: 'Proficiência total: artigos densos, relatórios e liderança.',
    lessons: [
      'Reading dense academic and technical papers',
      'Writing long-form technical reports',
      'Leading meetings and driving decisions in English',
      'Mentoring: giving structured feedback',
      'Subtle register: formal vs casual in global teams',
      'Listening: native-speed multi-speaker debates',
      'Writing public technical blog posts',
      'Handling conflict and escalation in writing',
      'Executive summaries: compressing complexity',
      'Mock interview: full senior-level session',
    ],
  },
];

export const ALL_TRACKS = [
  ...TECH_DISCIPLINES.map((d) => ({ ...d, world: 'academic', kind: 'tech' })),
  ...ENGLISH_LEVELS.map((d) => ({ ...d, world: 'english', kind: 'english' })),
];
